### ISSUE TITLE
Mismatched/Incorrect Input Prompts

### ISSUE THREAD

**Issue by OkyDooky** [SYtor/Kanji-Dojo#26] opened 2023-03-20 01:00 UTC
Hi, there. Thank you for creating this app, first of all.
I just tried it out for the first time today and encounted a pretty serious issue on my first Hiragana Writing session. お was the first one and went fine. But, when I tried い (the next one shown), it kept rejecting my attempts to draw the first stroke. I thought it was just being very strict on following the nuances in the font/style used, but then it gave a red "hint" to draw a short dtroke straight across the top. I did that and it accepted it as the first stroke. The second stroke was the same deal, except it prompted a vertical stroke down the middle. That worked...
When I tried to draw い for the second stage, I completely missed what the first stroke was "supposed" to be, but it accepted what I tried to draw, and the second one was the second stroke of お!

I'll continue and let you know which other ones it does this for and how often.

The device I'm using is a Galaxy Note 3 running Lineage OS. Android version is 11.

**Comment by syt0r** [comment] 2023-03-20 09:46
Do you mean that during review of one character you had to write stroke from another character in the practice to pass? I never had such issue, did it happen only once?

**Comment by OkyDooky** [comment] 2023-03-27 04:34
Sorry for the late response. Yes, it seems that is the case. I tried the first set of Hiragana given a second time and had no issue. But, when I tried the second set, just now, I had it happen again. I was first prompted to write こ and did so successfully. Then, I was prompted to write さ and was "failing". The first two strokes were leftovers from こ, while the third was, I think, the first from さ.
Not sure why it is doing this. :/

**Comment by OkyDooky** [comment] 2023-03-27 06:16
Oh, weird. Now it's doing it for き, where it's asking for こ's strokes for the first two and then さ's for the last two. This is the same session, btw.
Now, it seems to be breaking down even more, with each new character. It started using the next character's strokes and cycling through spme of the older one's. It seems to be following the sequence, underneath, but it's just mismatched from what is being displayed. And that is weird that it didn't do it for the round before.
Actually, I tried stopping the session and restarting the app, then going back into the session and everything seemed to be in alignment again. It's just odd that it gets out of alignment at all.

**Comment by kanji-deshi** [comment] 2023-05-22 10:47
This bug ocurred very rarely for me on 1.2. However it seems that https://github.com/syt0r/Kanji-Dojo/issues/25 made it worse as now every time it loads there is a chance the session breaks.

**Comment by kanji-deshi** [comment] 2023-05-22 11:35
First the loading screen appears, then it goes back to the previous character, you press the next button again, and then it's broken.

**Comment by syt0r** [comment] 2023-05-23 06:48
What device and OS version do you have? And does it happens only when practicing kana or kanji as well?

**Comment by kanji-deshi** [comment] 2023-05-24 15:59
Yes, it affects kanji, too. It seems there is a race condition where the characters and the strokes get out of sync. I should have checked this earlier, but I wasn't able to reproduce it with the latest release. It happened on a debug build based on the latest commit, but it stopped happening even there. There's not even a loading screen between characters anymore. I tried to trigger it by using up system resources and succeded once.

**Comment by syt0r** [comment] 2023-05-24 20:04
I see. I tried to add artificial delays to loading process for each character but even with loading screens I couldn't reproduce this issue. I hope this is not a bug of framework, because there are still some common unresolved crashes and I'm seeing different behaviour of recompositions on different platforms/devices. The next release will have updated frameword(compose) version so it might help

**Comment by ghost** [comment] 2023-09-22 07:26
Hello! I am encountering this same issue (the app expects me to draw other kanji than the one shown on screen). I can constantly reproduce this bug on a Huawei Matepad (HarmonyOS 3), app ver 1.4, by doing one the following:
1. Leave the app in the background for some time (usually 1 hour) then start a large study session (>30 characters, constantly happens at 90)
2. Progress through a large study session (>30 characters) quickly (draw a kanji in <3 seconds)
After 5-10 kanji I get a loading screen for a few seconds, a new kanji to practice is displayed but the app expects another one (can't figure out if prevously shown or not). Starting a new session without closing the app makes the issue occur again. Closing the app and starting a new session usually solves it for some time.
If there is any way I can help, please let me know. Many thanks!

**Comment by syt0r** [comment] 2023-09-25 08:19
@macaronickitten thanks for the tip, I'll try to do something similar to test

**Comment by syt0r** [comment] 2023-10-12 13:32
Can anyone verify if it still happens in newest version of the app, like 1.6 or even 1.5? 

I also currently updating input handling logic there for the next version just in case, so I would appreciate if someone could take a look and tell if it helps

https://drive.google.com/file/d/1tWkrfPjacEMglTUvcII1j3KzSJ7-4mpI/view?usp=sharing

I've changed package name for this test version so you can safely install it alongside with main version of the app

**Comment by ghost** [comment] 2023-10-14 08:27
> Can anyone verify if it still happens in newest version of the app, like 1.6 or even 1.5?
> 
> I also currently updating input handling logic there for the next version just in case, so I would appreciate if someone could take a look and tell if it helps
> 
> https://drive.google.com/file/d/1tWkrfPjacEMglTUvcII1j3KzSJ7-4mpI/view?usp=sharing
> 
> I've changed package name for this test version so you can safely install it alongside with main version of the app

Hello, the bug still happens in version 1.6 . Started a practice session on JLPTN5 level with the 79 kanji, solved 8 in a row correctly, missed 食, then when I had to retry it later the app expected other strokes, as alluded by the stroke guide that appears after a few wrong strokes. Will try the version in your link soon. Thank you!

**Comment by syt0r** [comment] 2023-12-06 08:27
New version 1.7 is live everywhere, please reopen if it happens again with updated stroke input logic

**Closed as completed by syt0r** 2023-12-06 08:27 UTC
Labels: bug
